sudo: required
os: linux
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

script:
  - docker version
  - docker build --no-cache --tag ll/gamesvr-blackmesa-freeplay --tag lacledeslan/gamesvr-blackmesa-freeplay --build-arg BUILDNODE=TravisCI -f Dockerfile.linux .
  - docker run -it --rm ll/gamesvr-blackmesa-freeplay ./ll-tests/gamesvr-blackmesa-freeplay.sh

notifications:
  slack:
    secure: r9V7srcktrZNSyoaZ5zNUwuT4OAx6W295zwDq5YyctvxUQIErL8ZXD46TWR3tS7LbaIZiRPmnYVnQoOJiYgdqhyI2KOdHyBtg8laP0t7kZoqSct4MbDPw6wc4ZSuNq6RKpKMgjHZisuMgsGwCgGXv7Xs4YfABc2OlKkR303BJT4SzIjBNQkwFX9mz53HcKODkJkd1wjQI0wSWlZk+71m30kbZyHmo/9K+Y3GPZLEsOAFwQmY/mVggbeE3F+Ampv2KRptb1FcuCPERoPQ4Eyi6n6Eo8esAdn6bxTwaO9todocLiDnQcPC0UUdOk5itSwNd7CF0Nk8hR0AJpQkuREY4b44SKTl06xmPU1nnaynxHmY+tF4jf8knTCRBxRdT95nkZ/9HjiKDk6/N1o/OQs25voL3UIEnyKAf7OWMPmL/IX178VgRbt8NUfmbNezN6X/gj5+mm+tYMvRtQkr5ovnge2NKm6iM+i4wLTksDZfuFnjipCYL8ccazb6X0E1ewIRrK4zZAIPsgmsrnXwq3PBG9CbNK1r5Y3VCwCssRp4zfe3eo0g12zEklJrXL5COH0FpE7EzAreCxWC2/u8eKJL4SzhfCoOUWd5SjJCsCKEJxGoAzhd+oD3oz4dBJ3EY5EOpF2417ZhKyNlBf8i6n10clb6rus1AfdIfuAY6klGBqU=

before_deploy:
  - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS";
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-blackmesa-freeplay
  on:
    branch: master
after_deploy:
  - curl -X POST https://hooks.microbadger.com/images/lacledeslan/ggamesvr-blackmesa-freeplay/$MICROBADGER_TOKEN
